# Imports

In [108]:
import pandas as pd

# 1. Leitura dos dados

In [109]:
data = pd.read_csv('dataset\\RECLAMEAQUI_PAODEACUCAR.csv')

data

,ID,TEMA,LOCAL,TEMPO,CATEGORIA,STATUS,DESCRICAO,URL,ANO,MES,DIA,DIA_DO_ANO,SEMANA_DO_ANO,DIA_DA_SEMANA,TRIMETRES,CASOS
0,147765939,Preço na prateleira diferente do que está no c...,Campinas - SP,2022-01-08,Pão de Açúcar<->Supermercados<->Propaganda eng...,Resolvido,Alegando erro operacional mas que se repete se...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
1,147699053,UTILIZAÇÃO INDEVIDA DOS MEUS STIX,São Paulo - SP,2022-01-08,Clubes de Compras e Vantagens<->Pão de Açúcar<...,Resolvido,Estou chocada pois acabei de ver um e-mail na ...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
2,147700991,Não recebi meu estorno,Rio de Janeiro - RJ,2022-01-08,Supermercados<->Não encontrei meu problema<->P...,Respondida,"Fiz um reclamação semana passada, devido uma c...",https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
3,147703729,Tiraram pontos stix da conta.,São Paulo - SP,2022-01-08,Clubes de Compras e Vantagens<->Pão de Açúcar<...,Respondida,Conclui minha a meta gasto mensal no programa ...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
4,147705769,[Editado pelo Reclame Aqui] pontos stix,São Paulo - SP,2022-01-08,Clubes de Compras e Vantagens<->Pão de Açúcar<...,Respondida,Pela segunda vez no mesmo mês tive meus pontos...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,150028525,Não entregam nunca no horário limite,São Paulo - SP,2022-12-09,Atraso na entrega<->Supermercados<->Pão de Açúcar,Respondida,"Sempre que peço no site do pão de açúcar, agen...",https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18
996,150029021,Pão de Açúcar e a dívida que desconheço.,São Paulo - SP,2022-12-09,Pão de Açúcar<->Não encontrei meu problema<->C...,Não respondida,"A empresa ITAPEVA, tem negativado meu nome com...",https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18
997,150029875,Desconto 20% em Vinhos não concedido,Rio Negrinho - SC,2022-12-09,Pão de Açúcar<->Divergência de valores<->Bebidas,Não respondida,No dia 22/08/2022 realizei uma compra de vinho...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18
998,149991011,itens faltantes,São Paulo - SP,2022-12-09,Pão de Açúcar<->Hipermercados<->Entrega faltan...,Não respondida,Fiz uma compra no site do pão de açucar e veio...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18
999,150027043,Pizza de Mussarela Estragada,São Paulo - SP,2022-12-09,Pão de Açúcar<->Não encontrei meu problema<->E...,Não respondida,No dia 09/09/22 comprei uma pizza de mussarela...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,12,9,343,49,4,4,18

# 2. Análise estrutural do dataset

In [110]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             1000 non-null   int64
 1   TEMA           1000 non-null   object
 2   LOCAL          1000 non-null   object
 3   TEMPO          1000 non-null   object
 4   CATEGORIA      1000 non-null   object
 5   STATUS         1000 non-null   object
 6   DESCRICAO      1000 non-null   object
 7   URL            1000 non-null   object
 8   ANO            1000 non-null   int64
 9   MES            1000 non-null   int64
 10  DIA            1000 non-null   int64
 11  DIA_DO_ANO     1000 non-null   int64
 12  SEMANA_DO_ANO  1000 non-null   int64
 13  DIA_DA_SEMANA  1000 non-null   int64
 14  TRIMETRES      1000 non-null   int64
 15  CASOS          1000 non-null   int64
dtypes: int64(9), object(7)
memory usage: 125.1+ KB

In [111]:
# Transformar todos os nomes das colunas em letras minúsculas
data.columns = data.columns.str.lower()

data.columns.tolist()

['id',
 'tema',
 'local',
 'tempo',
 'categoria',
 'status',
 'descricao',
 'url',
 'ano',
 'mes',
 'dia',
 'dia_do_ano',
 'semana_do_ano',
 'dia_da_semana',
 'trimetres',
 'casos']

In [112]:
# Primeira visão de variáveis categóricas chave. Contagem de valores únicos
print(f"~> Número de temas únicos: {data['tema'].nunique()}")
print(f"~> Número de locais únicos: {data['local'].nunique()}")
print(f"~> Número de datas únicas: {data['tempo'].nunique()}")
print(f"~> Número de categorias únicas: {data['categoria'].nunique()}")
print(f"~> Número de descrições únicas: {data['descricao'].nunique()}")
print(f"~> Padrões de status únicos: {data['status'].unique().tolist()}")

~> Número de temas únicos: 944
~> Número de locais únicos: 135
~> Número de datas únicas: 71
~> Número de categorias únicas: 210
~> Número de descrições únicas: 989
~> Padrões de status únicos: ['Resolvido', 'Respondida', 'Em réplica', 'Não respondida', 'Não resolvido']

# 3. Análise Exploratória de Dados

In [113]:
# Realizar a verificação se há alguma coluna com pelo menos um valor nulo.
print('_' * 42)
print(f'|{'Valores nulos por coluna': ^40}|')
print('-' * 42)

for i in data.columns:
    print(f'|{i: <20}',end='')
    print(f'{data[i].isna().sum(): >20}|')
    
print('-' * 42)

__________________________________________
|        Valores nulos por coluna        |
------------------------------------------
|id                                     0|
|tema                                   0|
|local                                  0|
|tempo                                  0|
|categoria                              0|
|status                                 0|
|descricao                              0|
|url                                    0|
|ano                                    0|
|mes                                    0|
|dia                                    0|
|dia_do_ano                             0|
|semana_do_ano                          0|
|dia_da_semana                          0|
|trimetres                              0|
|casos                                  0|
------------------------------------------

In [114]:
print('_' * 110)
print(f'|{'Valores nulos por coluna': ^78}|')
print('-' * 110)
data.describe().T

______________________________________________________________________________________________________________
|                           Valores nulos por coluna                           |
--------------------------------------------------------------------------------------------------------------

,count,mean,std,min,25%,50%,75%,max
id,1000.0,1.485025e+08,1.139302e+06,146345143.0,147598303.5,148473420.0,149516314.5,150438193.0
ano,1000.0,2.022000e+03,0.000000e+00,2022.0,2022.0,2022.0,2022.0,2022.0
mes,1000.0,7.272000e+00,2.506052e+00,1.0,7.0,8.0,8.0,12.0
dia,1000.0,1.551700e+01,7.397461e+00,7.0,9.0,14.0,21.0,31.0
dia_do_ano,1000.0,2.053620e+02,7.769883e+01,8.0,194.0,221.0,243.0,343.0
semana_do_ano,1000.0,2.950700e+01,1.113759e+01,1.0,28.0,32.0,35.0,49.0
dia_da_semana,1000.0,2.813000e+00,1.864808e+00,0.0,1.0,3.0,4.0,6.0
trimetres,1000.0,2.786000e+00,7.891938e-01,1.0,3.0,3.0,3.0,4.0
casos,1000.0,1.663000e+01,5.821597e+00,2.0,14.0,17.0,21.0,33.0

In [115]:
data.nunique()

id                996
tema              944
local             135
tempo              71
categoria         210
status              5
descricao         989
url              1000
ano                 1
mes                12
dia                22
dia_do_ano         71
semana_do_ano      21
dia_da_semana       7
trimetres           4
casos              25
dtype: int64

In [ ]:
data = data.drop_duplicates(subset=data.columns.drop('url')).copy()

In [117]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 996 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             996 non-null    int64
 1   tema           996 non-null    object
 2   local          996 non-null    object
 3   tempo          996 non-null    object
 4   categoria      996 non-null    object
 5   status         996 non-null    object
 6   descricao      996 non-null    object
 7   url            996 non-null    object
 8   ano            996 non-null    int64
 9   mes            996 non-null    int64
 10  dia            996 non-null    int64
 11  dia_do_ano     996 non-null    int64
 12  semana_do_ano  996 non-null    int64
 13  dia_da_semana  996 non-null    int64
 14  trimetres      996 non-null    int64
 15  casos          996 non-null    int64
dtypes: int64(9), object(7)
memory usage: 132.3+ KB

# 4. Tratamento de Dados

## 4.1 Limpeza de espaços extras (strip)

In [118]:
# Remover espaços extras no início e fim das colunas de texto
#data.columns = data.columns.str.lower()
str_cols = ['tema', 'local', 'tempo', 'categoria', 'status', 'descricao']
for col in str_cols:
    data[col] = data[col].str.strip()

print('Strip aplicado nas colunas:', str_cols)

Strip aplicado nas colunas: ['tema', 'local', 'tempo', 'categoria', 'status', 'descricao']

C:\Users\rnxro\AppData\Local\Temp\ipykernel_102936\2216404565.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = data[col].str.strip()

## 4.2 Padronização de capitalização da coluna CATEGORIA

In [119]:
# Antes da padronização: checar variações de capitalização
print('Antes:')
cats_antes = data['categoria'].str.split('<->').explode().str.strip()
print(cats_antes[cats_antes.str.lower().str.contains('propaganda')].unique())

# Padronizar para title case (primeira letra maiúscula em cada palavra)
data['categoria'] = data['categoria'].str.title()

print('\nDepois:')
cats_depois = data['categoria'].str.split('<->').explode().str.strip()
print(cats_depois[cats_depois.str.lower().str.contains('propaganda')].unique())

Antes:
['Propaganda enganosa' 'Propaganda Enganosa']

Depois:
['Propaganda Enganosa']

C:\Users\rnxro\AppData\Local\Temp\ipykernel_102936\2290099108.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['categoria'] = data['categoria'].str.title()

## 4.3 Conversão da coluna TEMPO para datetime

In [120]:
# Converter TEMPO de string para datetime
data['tempo'] = pd.to_datetime(data['tempo'])

print('Tipo antes/depois da conversão:')
print(f'Tipo: {data["tempo"].dtype}')
print(data['tempo'].head())

Tipo antes/depois da conversão:
Tipo: datetime64[ns]
0   2022-01-08
1   2022-01-08
2   2022-01-08
3   2022-01-08
4   2022-01-08
Name: tempo, dtype: datetime64[ns]

C:\Users\rnxro\AppData\Local\Temp\ipykernel_102936\2940878062.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tempo'] = pd.to_datetime(data['tempo'])

## 4.4 Extração do Estado (UF) a partir da coluna LOCAL

In [121]:
# Extrair a sigla do estado (últimos 2 caracteres após ' - ')
data['estado'] = data['local'].str.extract(r'- ([A-Z]{2})$')

print('Distribuição por Estado:')
print(data['estado'].value_counts())

Distribuição por Estado:
estado
SP    703
RJ     84
DF     42
CE     26
GO     25
MG     23
BA     19
PE     18
PB      9
PR      8
SE      8
MS      5
RS      4
SC      4
PI      4
RN      3
AL      3
ES      2
MT      2
AM      2
PA      1
Name: count, dtype: int64

C:\Users\rnxro\AppData\Local\Temp\ipykernel_102936\988116349.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['estado'] = data['local'].str.extract(r'- ([A-Z]{2})$')

## 4.5 Explosão da coluna CATEGORIA (separador `<->`)

In [122]:
# Criar versão explodida para análises por categoria individual
# (mantemos o dataframe original intacto e criamos um auxiliar)
data_cats = data.copy()
data_cats['categoria'] = data_cats['categoria'].str.split('<->')
data_cats = data_cats.explode('categoria').reset_index(drop=True)
data_cats['categoria'] = data_cats['categoria'].str.strip()

# Remover a categoria que é o próprio nome da empresa
data_cats = data_cats[~data_cats['categoria'].str.contains('Pão De Açúcar|Pao De Acucar', case=False)]

print(f'Shape original: {data.shape}')
print(f'Shape explodido: {data_cats.shape}')
print('\nTop 10 categorias:')
print(data_cats['categoria'].value_counts().head(10))

Shape original: (996, 17)
Shape explodido: (2395, 17)

Top 10 categorias:
categoria
Supermercados                              481
Propaganda Enganosa                        237
Não Encontrei Meu Problema                 173
Problemas Com O Atendimento                168
Pontos                                     158
Clubes De Compras E Vantagens              151
Mau Atendimento                            136
Problema Com Entrega De Produto-Compras    134
Estorno Do Valor Pago                       75
Divergência De Valores                      53
Name: count, dtype: int64

## 4.6 Verificação final do dataset tratado

In [123]:
print('=== Dataset após tratamentos ===')
print(f'Shape: {data.shape}')
print(f'\nTipos das colunas:')
print(data.dtypes)
print(f'\nNulos remanescentes:')
print(data.isnull().sum())
data.head(3)

=== Dataset após tratamentos ===
Shape: (996, 17)

Tipos das colunas:
id                        int64
tema                     object
local                    object
tempo            datetime64[ns]
categoria                object
status                   object
descricao                object
url                      object
ano                       int64
mes                       int64
dia                       int64
dia_do_ano                int64
semana_do_ano             int64
dia_da_semana             int64
trimetres                 int64
casos                     int64
estado                   object
dtype: object

Nulos remanescentes:
id               0
tema             0
local            0
tempo            0
categoria        0
status           0
descricao        0
url              0
ano              0
mes              0
dia              0
dia_do_ano       0
semana_do_ano    0
dia_da_semana    0
trimetres        0
casos            0
estado           1
dtype: int64

,id,tema,local,tempo,categoria,status,descricao,url,ano,mes,dia,dia_do_ano,semana_do_ano,dia_da_semana,trimetres,casos,estado
0,147765939,Preço na prateleira diferente do que está no c...,Campinas - SP,2022-01-08,Pão De Açúcar<->Supermercados<->Propaganda Eng...,Resolvido,Alegando erro operacional mas que se repete se...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24,SP
1,147699053,UTILIZAÇÃO INDEVIDA DOS MEUS STIX,São Paulo - SP,2022-01-08,Clubes De Compras E Vantagens<->Pão De Açúcar<...,Resolvido,Estou chocada pois acabei de ver um e-mail na ...,https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24,SP
2,147700991,Não recebi meu estorno,Rio de Janeiro - RJ,2022-01-08,Supermercados<->Não Encontrei Meu Problema<->P...,Respondida,"Fiz um reclamação semana passada, devido uma c...",https://www.reclameaqui.com.br//pao-de-acucar/...,2022,1,8,8,1,5,1,24,RJ